In [1]:
import numpy as np

1 Створіть одновимірний масив (вектор) з сумами добутків двох попередніх чисел та їхнього суми, починаючи з 1, та виведіть його значення. 

In [9]:
n = 5
vector = [1] * n  # Починаємо з першого елементу, який завжди 1

# Заповнюємо вектор
for i in range(2, n):
    vector[i] = vector[i - 2] * vector[i - 1] + vector[i - 1] + vector[i - 2]

# Виводимо вектор
print(vector)

[1, 1, 3, 7, 31]


2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями добутків найближчого меншого парного числа на кожне натуральне число, починаючи з 1, та виведіть його значення. 

In [10]:
n = 3
m = 3

# Ініціалізуємо матрицю нулями
matrix = np.zeros((n, m), dtype=int)

# Заповнюємо матрицю
current_number = 1
for i in range(n):
    for j in range(m):
        # Знаходимо найближче менше парне число
        nearest_even = current_number - 1 if current_number % 2 == 1 else current_number - 2
        # Обчислюємо значення та записуємо його в матрицю
        matrix[i, j] = nearest_even * current_number
        current_number += 1

# Виводимо матрицю
matrix

array([[ 0,  0,  6],
       [ 8, 20, 24],
       [42, 48, 72]])

3 Створіть масив розміром 5x5, заповніть його випадковими дійсними числами від 0 до 1 та знайдіть відсоток чисел, які є простими. 

In [12]:
n = 5
m = 5

# Ініціалізуємо матрицю випадковими дійсними числами від 0 до 1
matrix = np.random.rand(n, m)

# Функція для перевірки, чи є число простим
def is_prime(number):
    if number <= 1:
        return False
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            return False
    return True

# Векторізуємо функцію is_prime для застосування до всіх елементів матриці
is_prime_vectorized = np.vectorize(is_prime)

# Рахуємо кількість простих чисел у матриці
prime_count = np.sum(is_prime_vectorized(matrix))

# Знаходимо відсоток простих чисел
percentage_prime = (prime_count / (n * m)) * 100

# Виводимо матрицю та відсоток простих чисел
matrix, percentage_prime

(array([[0.34471176, 0.4441173 , 0.0500898 , 0.95065118, 0.16257072],
        [0.2113853 , 0.18031729, 0.12956058, 0.8468302 , 0.56466535],
        [0.28910983, 0.00486298, 0.05061793, 0.64117349, 0.19934835],
        [0.46047937, 0.19112333, 0.98676104, 0.83924513, 0.66050306],
        [0.99877338, 0.93038653, 0.87355391, 0.43177691, 0.26617811]]),
 0.0)

4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від -1.1 до 1.1 та виведіть його значення. 

In [13]:
n = 4
m = 4

# Генеруємо масив з випадковими числами в заданому діапазоні
matrix = np.random.uniform(-1.1, 1.1, size=(n, m))

# Виводимо матрицю
matrix

array([[-0.34566362, -0.05877554,  0.256782  , -0.52198315],
       [ 0.64193162, -0.162163  , -0.42446358,  0.23075581],
       [ 0.33288817,  0.95618056,  1.06983384, -0.79665979],
       [ 0.87599645,  0.0568216 ,  0.8587687 , -1.00855651]])

5 Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами в діапазоні від 15 до 25 та виконайте на них поелементні операції додавання, віднімання та множення. 

In [14]:
n = 4

# Заповнюємо два масиви випадковими цілими числами в діапазоні від 15 до 25
array1 = np.random.randint(15, 26, size=n)
array2 = np.random.randint(15, 26, size=n)

# Виконуємо поелементне додавання, віднімання та множення
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

# Виводимо обидва масиви та результати операцій
array1, array2, addition_result, subtraction_result, multiplication_result

(array([24, 18, 16, 24]),
 array([17, 16, 18, 22]),
 array([41, 34, 34, 46]),
 array([ 7,  2, -2,  2]),
 array([408, 288, 288, 528]))

6 Створіть два вектори розміром 4, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток. 

In [15]:
n = 4

# Заповнюємо два вектори довільними дійсними числами
vector1 = np.random.rand(n)
vector2 = np.random.rand(n)

# Знаходимо скалярний добуток векторів
scalar_product = np.dot(vector1, vector2)

# Виводимо обидва вектори та скалярний добуток
vector1, vector2, scalar_product

(array([0.67747237, 0.30252913, 0.09931562, 0.54663984]),
 array([0.90516159, 0.74970969, 0.15238835, 0.14604467]),
 0.9349993631427578)

7 Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 12 та перемножте їх між собою. 

In [16]:
n1, m1 = 2, 3
n2, m2 = 3, 3

# Заповнюємо першу матрицю випадковими цілими числами в діапазоні від 1 до 12
matrix1 = np.random.randint(1, 13, size=(n1, m1))

# Заповнюємо другу матрицю випадковими цілими числами в діапазоні від 1 до 12
matrix2 = np.random.randint(1, 13, size=(n2, m2))

# Перемножуємо матриці між собою
result_matrix = np.dot(matrix1, matrix2)

# Виводимо обидві матриці та результат перемноження
matrix1, matrix2, result_matrix

(array([[ 3, 12,  9],
        [12, 12,  5]]),
 array([[ 6,  5,  5],
        [ 6,  6,  1],
        [ 5, 10,  1]]),
 array([[135, 177,  36],
        [169, 182,  77]]))

8 Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю. 

In [17]:
matrix = np.random.randint(1, 8, size=(2, 2))

# Знаходимо обернену матрицю (якщо можливо)
try:
    inverse_matrix = np.linalg.inv(matrix)
except np.linalg.LinAlgError:
    inverse_matrix = "Обернена матриця не існує"

# Виводимо початкову матрицю та обернену матрицю
matrix, inverse_matrix

(array([[1, 1],
        [4, 7]]),
 array([[ 2.33333333, -0.33333333],
        [-1.33333333,  0.33333333]]))

 9 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 5 до 10 та транспонуйте її. 

In [27]:
n = 3

# Заповнюємо матрицю випадковими дійсними числами в діапазоні від 5 до 10
matrix = np.random.uniform(5, 10, size=(n, n))

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix)

# Виводимо початкову матрицю та транспоновану матрицю
matrix, transposed_matrix


(array([[9.7295147 , 6.41974964, 7.07530937],
        [8.2965426 , 6.78267854, 8.51631276],
        [9.60796197, 9.65691817, 7.83647348]]),
 array([[9.7295147 , 8.2965426 , 9.60796197],
        [6.41974964, 6.78267854, 9.65691817],
        [7.07530937, 8.51631276, 7.83647348]]))

10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть  добуток матриці на вектор. 

In [28]:
n_rows = 3
n_cols = 4
vector_size = 4

# Заповнюємо матрицю випадковими дійсними числами від 0 до 1
matrix = np.random.rand(n_rows, n_cols)

# Заповнюємо вектор випадковими дійсними числами від 0 до 1
vector = np.random.rand(vector_size)

# Обчислюємо добуток матриці на вектор
result = np.dot(matrix, vector)

# Виводимо матрицю, вектор і результат добутку
matrix, vector, result

(array([[0.31814981, 0.93103808, 0.59857682, 0.08116268],
        [0.80908635, 0.11558783, 0.29693554, 0.24010876],
        [0.5494509 , 0.86507133, 0.74506173, 0.28468828]]),
 array([0.5235478 , 0.07711733, 0.58507925, 0.89014758]),
 array([0.66082745, 0.81997226, 1.04371054]))

11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть суму добутків елементів кожного рядка матриці на відповідний елемент вектору

In [30]:
n_rows = 2
n_cols = 3
vector_size = 3

# Заповнюємо матрицю випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(n_rows, n_cols))

# Заповнюємо вектор випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=vector_size)

# Змінюємо розмірність вектора
vector = vector[:, np.newaxis]

# Обчислюємо добуток матриці на вектор
result = np.dot(matrix, vector)

# Виводимо матрицю, вектор і результат
matrix, vector, result

(array([[10,  5,  6],
        [ 1,  1,  8]]),
 array([[9],
        [5],
        [1]]),
 array([[121],
        [ 22]]))

12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму всіх елементів обох матриць.

In [31]:

# Розмір матриць
n_rows = 2
n_cols = 2

# Заповнюємо першу матрицю випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(n_rows, n_cols))

# Заповнюємо другу матрицю випадковими цілими числами від 1 до 10
matrix2 = np.random.randint(1, 11, size=(n_rows, n_cols))

# Знаходимо суму всіх елементів обох матриць
sum_matrix = matrix1 + matrix2

# Виводимо обидві матриці та суму
matrix1, matrix2, sum_matrix

(array([[5, 9],
        [7, 5]]),
 array([[10,  6],
        [ 7,  7]]),
 array([[15, 15],
        [14, 12]]))

13 Створіть дві матриці розміром 9x9, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть суму їх елементів. 

In [33]:
n_rows = 9
n_cols = 9

# Заповнюємо першу матрицю випадковими дійсними числами від 0 до 1
matrix1 = np.random.rand(n_rows, n_cols)

# Заповнюємо другу матрицю випадковими дійсними числами від 0 до 1
matrix2 = np.random.rand(n_rows, n_cols)

# Знаходимо суму всіх елементів обох матриць
sum_matrix = matrix1 + matrix2

# Виводимо суму
np.sum(sum_matrix)

82.89319851702737

14 Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть суму елементів на побічній діагоналі. 

In [34]:
n = 5

# Заповнюємо матрицю випадковими дійсними числами в діапазоні від -10 до 10
matrix = np.random.uniform(-10, 10, size=(n, n))

# Знаходимо суму елементів на побічній діагоналі
sum_diagonal = np.trace(matrix)

# Виводимо матрицю та суму елементів на побічній діагоналі
matrix, sum_diagonal

(array([[ 2.36445781, -3.96120575,  6.49332595,  4.33483168,  4.88203449],
        [ 6.88049356, -6.92905696, -5.27133169, -9.32372415, -6.05795638],
        [-6.53979159,  8.85664593,  0.36094249, -8.95235512, -4.02134553],
        [ 0.65921943,  7.34311957, -2.60706071,  6.5901291 ,  7.82215914],
        [-5.00125384, -8.71277522, -7.23318017, -0.27069788, -9.56213143]]),
 -7.175658993575677)

In [ ]:
15 Створіть матрицю розміром 11x11, заповніть її випадковими дійсними числами в діапазоні 
від 0 до 1 та знайдіть вектор-стовпчик, що містить найбільший елемент у кожному стовпці матриці. 

In [35]:
n = 11

# Заповнюємо матрицю випадковими дійсними числами в діапазоні від 0 до 1
matrix = np.random.rand(n, n)

# Знаходимо індекси найбільших елементів у кожному стовпці
max_indices = np.argmax(matrix, axis=0)

# Створюємо вектор-стовпчик, що містить найбільший елемент у кожному стовпці матриці
max_elements = matrix[max_indices, range(n)]
max_elements = max_elements.reshape(-1, 1)

# Виводимо вектор-стовпчик
max_elements

array([[0.79163936],
       [0.9677472 ],
       [0.92543054],
       [0.89211471],
       [0.98670808],
       [0.99925873],
       [0.83440228],
       [0.99196249],
       [0.9681136 ],
       [0.83582995],
       [0.97229518]])

За допомогою цієї лабораторної я дослідив способи заповнення масивів, їх перемноження, 
додавання, знаходження найбільших елементів, транспонування і обернення матриці.